alarm/urls.py
# alarms/urls.py
from django.urls import path
from . import views

app_name = 'alarm'

urlpatterns = [
    path('', views.Alert.as_view()),
    path('siren/<int:location_pk>', views.siren, name='siren'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from alarm import views

from django_otp.admin import OTPAdminSite

class OTPAdmin(OTPAdminSite):
    pass

from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)
urlpatterns = [
    path('admin/', admin_site.urls),
    path('dadmin/', admin.site.urls),
    path('', include('map.urls')),
    path('account/', include('account.urls')),
    path('Alert/', include('alarm.urls')),

]

map/urls.py
from django.urls import path, include

from . import views

app_name = 'map'

urlpatterns = [
    path('', views.main, name='main'),
    path('cctv/<int:location_pk>/', views.cctv, name='cctv'),
    path('cctv/check/<int:pk>/', views.check, name='check'),
    path('record/', views.record, name='record'),
    path('lists/police/', views.police_list, name='police-list'),
    path('lists/guard/', views.guard_list, name='guard-list'),
    path('send/<int:alarm_pk>/', views.send, name='send')
]

map/models.py
from django.db import models

from config import settings


class Location(models.Model):
    management = models.CharField(max_length=30)
    S_address = models.TextField(null=True)
    L_address = models.TextField(null=True)
    purpose = models.TextField(null=True)
    camera_num = models.IntegerField(null=True)
    camera_pixel = models.IntegerField(null=True)
    shoot_info = models.TextField(null=True)
    storage_days = models.IntegerField(null=True)
    installed_date = models.TextField(null=True)
    phone = models.TextField(null=True)
    latitude= models.TextField(null=True)
    longitude = models.TextField(null=True)
    data_date=  models.DateField(null=True)
    station = models.ForeignKey('account.Station', on_delete=models.CASCADE)

    def __str__(self):
        return self.station.name +"-"+str(self.pk)

map/views.py
import base64
import hashlib
import hmac
import time
import requests
import json
from . import keys

from django.shortcuts import render, redirect
from django.urls import reverse

from account.models import Profile, Guard, Station
from alarm.models import Alarm

# path = str(os.getcwd()) + "/map/static/data/"
# file_list = os.listdir(path)
# file_list_csv = [file for file in file_list if file.endswith(".csv")]
#
# data = []
# for file in file_list_csv:
#     full_path = path + str(file)
#     f = open(full_path, "r", encoding='cp949')
#     lines = f.readlines()
#     l = []
#     for line in lines:
#         l.append(line.split(','))
#     f.close()
#     data += l[1:]
from .models import Location

def main(request):
    if not request.user.is_authenticated:
        return redirect(reverse("account:login"))
    else:
        current_user = Profile.objects.get(user=request.user)
        # data = Location.objects.filter(station=current_user.location)
        alarms = Alarm.objects.filter(checked=False).filter(station=current_user.station.name)
        return render(request, "map/main.html", {'alarms':alarms})

def cctv(request, location_pk):
    # location = Location.objects.get(pk=location_pk)
    alarm = Alarm.objects.filter(location_pk=location_pk).get(checked=False)
    return render(request, "map/cctv.html", {'alarm': alarm, 'location_pk': location_pk})


def check(request, pk):
    alarm = Alarm.objects.get(pk=pk)
    alarm.checked = True
    alarm.save()
    return redirect("map:main")


def record(request):
    current_user = Profile.objects.get(user=request.user)
    alarms = Alarm.objects.filter(station=current_user.station.name)
    return render(request, "map/record.html", {'alarms':alarms, 'station': current_user.station.name})

def police_list(request):
    current_user = Profile.objects.get(user=request.user)
    polices = Profile.objects.filter(station=current_user.station)
    return render(request, "map/police_list.html", {'polices':polices,'station':current_user.station.name})

def guard_list(request):
    current_user = Profile.objects.get(user=request.user)
    guards = Guard.objects.filter(station=current_user.station)
    return render(request, "map/guard_list.html", {'guards':guards, 'station':current_user.station.name})

def make_signature(string):
    secret_key = bytes(keys.secret_key, 'UTF-8')
    string = bytes(string, 'UTF-8')
    string_hmac = hmac.new(secret_key, string, digestmod=hashlib.sha256).digest()
    string_base64 = base64.b64encode(string_hmac).decode('UTF-8')
    return string_base64

def send(request, alarm_pk):
    url = "https://sens.apigw.ntruss.com"
    uri = "/sms/v2/services/" + keys.service_id + "/messages"
    api_url = url + uri
    timestamp = str(int(time.time() * 1000))
    access_key = keys.access_key
    string_to_sign = "POST " + uri + "\n" + timestamp + "\n" + access_key
    signature = make_signature(string_to_sign)

    alarm = Alarm.objects.get(pk=alarm_pk)
    location = Location.objects.get(pk=alarm.location_pk)
    # 해당 위치의 station을 불러와서, 그 관할서의 guard들을 불러옴.
    address = alarm.address
    station = Station.objects.get(name=alarm.station)
    guards = Guard.objects.filter(station=station.pk)

    message = "{} 확인요망".format(address)

    headers = {
        'Content-Type': "application/json; charset=UTF-8",
        'x-ncp-apigw-timestamp': timestamp,
        'x-ncp-iam-access-key': access_key,
        'x-ncp-apigw-signature-v2': signature
    }


    for guard in guards:
        phone = guard.phone
        body = {
            "type": "SMS",
            "contentType": "COMM",
            "from": "01048046921",
            "content": message,
            "messages": [{"to": phone}]
        }
        body2 = json.dumps(body)
        response = requests.post(api_url, headers=headers, data=body2)
        response.raise_for_status()
    return redirect("map:cctv", location.pk)

def make_signature(string):
    secret_key = bytes(keys.secret_key, 'UTF-8')
    string = bytes(string, 'UTF-8')
    string_hmac = hmac.new(secret_key, string, digestmod=hashlib.sha256).digest()
    string_base64 = base64.b64encode(string_hmac)
    return string_base64

templates/map/cctv.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{ alarm.address }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Style -->
    <style type="text/css">
        #btn {
            margin-top: 10px;
        }

        #contents-wrapper {

            width: 100%;
            height: 100%;
            padding: 10px;
            position: absolute;
            overflow: hidden;

        }


        #contents {
            border: 1px solid #487BE1;
            width: 80%;
            height: 100%;
            float: left;
            padding: 10px;

        }


        #button {
        {#border: 1px solid #487BE1;#} width: 20%;
            float: right;
            padding: 10px;

        }
    </style>
    <!--# Style -->
    <!-- Custom styles for this template -->
    <link href="{% static "css/simple-sidebar.css" %}" rel="stylesheet">
    <script type="text/javascript"
            src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=cu5hnzqfla"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<div class="d-flex" id="wrapper">
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <h3 style="padding:10px 10px 0 10px;">실시간 CCTV 영상 - 주소: {{ alarm.address }}</h3>
        <div id="contents-wrapper" style="height:90%;">
            <div id="contents">
                <img src="http://192.168.137.90:8081/?action=stream" alt="This is a static snapshot"
                     style=width:100%;height:100%;>
            </div>
            <!-- button -->
            <div id="button" class="container">
                <div class="row">
                    <div class="col-12" align="center">
                        <h3>알람 발생 시간</h3>
                        <h4>{{ alarm.date }}</h4><br>
                        <div class="btn-group-vertical" style="width:100%;">
                            <button type="button" id="siren" onclick = "location.href = '{% url "alarm:siren" location_pk %}'" class="btn btn-danger">사이렌 울리기</button>
                            <button type="button" id="send" class="btn btn-primary">메시지 보내기</button>
                            <button type="button" id="check" class="btn btn-success">확인완료</button>
{#                            <button type="button" id="btn" class="btn btn-success" style="margin:0;">창 닫기</button>#}
                            {#                                <button type="button" id="btn" class="btn btn-primary">사이렌 울리기</button>#}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /#button -->
        </div>
    </div>
    <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- Menu Toggle Script -->
<script type="text/javascript">
  $("#check").click(function(){
      $.ajax({
          type: "POST",
          url: "{% url 'map:check' alarm.pk %}",
          data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
          success: function(response){
              alert('확인완료')
              opener.parent.location.reload();
              window.close();
          },
          error: function(request, status, error){
              alert(error)
          },
      });
  })

  $("#siren").click(function(){
      $.ajax({
          type: "GET",
          url: "{% url 'alarm:siren' location_pk %}",
          success: function(response){
              alert('사이렌을 울렸습니다.');
          },
          error: function(request, status, error){
              alert(error)
          },
      });
  })
    $("#send").click(function () {
        $.ajax({
            type: "POST",
            url: "{% url 'map:send' alarm.pk %}",
            data: {'csrfmiddlewaretoken': '{{ csrf_token }}',},
            async:true,
            success: function (response) {
                alert('성공')
            },
            error: function (request, status, error) {
                alert(error)
            },
        });
    });

</script>

templates/map/main.html
{% extends "base.html" %}
{% block content %}
    {% csrf_token %}
    <script type="text/javascript"
            src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=u7319e28n1"></script>
    <div class="container-fluid" style="padding:0px;">
        <div id="map" style="width:100%;height:100%;"></div>
    </div>
    <script>
        var map = new naver.maps.Map('map', {
            center: new naver.maps.LatLng(37.5617306, 126.94367550000001),
            zoom: 15
        });
        var markers = [], infoWindows = [];

        {% for i in alarms %}
            var position = new naver.maps.LatLng({{ i.latitude }}, {{ i.longitude }});

            var marker = new naver.maps.Marker({
                map: map,
                position: position
            });
            var url = "{% url 'map:cctv' i.location_pk %}"
            var address = "{{ i.address }}"
            var infoWindow = new naver.maps.InfoWindow({
                content:
                    '<a href=\"#\" onclick=\"window.open(\''+url+'\', width=200, height=200)\" style=\"width:auto; text-align:center;padding:10px;\">'+address+'</a>'
            });
            markers.push(marker);
            infoWindows.push(infoWindow);
        {% endfor %}

        naver.maps.Event.addListener(map, 'idle', function () {
            updateMarkers(map, markers);
        });

        function updateMarkers(map, markers) {
            var mapBounds = map.getBounds();
            var marker, position;

            for (var i = 0; i < markers.length; i++) {

                marker = markers[i];
                position = marker.getPosition();

                if (mapBounds.hasLatLng(position)) {
                    showMarker(map, marker);
                    marker.setAnimation(naver.maps.Animation.BOUNCE);
                } else {
                    hideMarker(map, marker);
                }
            }
        }

        function showMarker(map, marker) {

            if (marker.setMap(null)) return;
            marker.setMap(map);
        }

        function hideMarker(map, marker) {

            if (!marker.setMap(map)) return;
            marker.setMap(null);
        }

        function getClickHandler(seq) {
            return function (e) {
                var marker = markers[seq],
                    infoWindow = infoWindows[seq];
                if (marker.getAnimation() !== null){
                    marker.setAnimation(null);
                }
                if (infoWindow.getMap()) {
                    infoWindow.close();
                } else {
                    infoWindow.open(map, marker);
                }
            }
        }

        function getClickHandler_2(infoWindow, marker) {
            return function (e) {
                infoWindow.open(map, marker)
            }
}

        for (var i = 0, ii = markers.length; i < ii; i++) {
            naver.maps.Event.addListener(markers[i], 'click', getClickHandler(i));
        }

    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script>
        username='{{ username }}';
        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/test/'+username+'/');

        chatSocket.onmessage = function(e) {
            console.log(e);
            var data = JSON.parse(e.data);
            var longitude = data['longitude'];
            var latitude = data['latitude'];
            var address = data['address'];
            var location_pk = data['location_pk'];
            var new_position = new naver.maps.LatLng(latitude, longitude)
            var new_marker = new naver.maps.Marker({
                map:map,
                position: new_position
            })
            new_marker.setAnimation(naver.maps.Animation.BOUNCE);
            var location_url = 'http://127.0.0.1:8000/cctv/'+location_pk;
            console.log(location_url)

            var new_infoWindow = new naver.maps.InfoWindow({
                content:
                    '<a href=\"#\" onclick=\"window.open(\''+location_url+'\', width=300, height=300)\" style=\"width:auto; text-align:center;padding:10px;\">'+address+'</a>'
            });
            naver.maps.Event.addListener(new_marker, 'click', getClickHandler_2(new_infoWindow, new_marker));
        };

        chatSocket.onopen=function (e) {
          console.log("연결 성공");
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    </script>
{% endblock %}