config/urls.py
from django.contrib import admin
from django.urls import path, include
from alarm import views

from django_otp.admin import OTPAdminSite

class OTPAdmin(OTPAdminSite):
    pass

from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)
urlpatterns = [
    path('admin/', admin_site.urls),
    path('dadmin/', admin.site.urls),
    path('', include('map.urls')),
    path('account/', include('account.urls')),
    path('Alert/', include('alarm.urls')),

]

map/urls.py
from django.urls import path, include

from . import views

app_name = 'map'

urlpatterns = [
    path('', views.main, name='main'),
    path('cctv/<int:location_pk>/', views.cctv, name='cctv'),
    path('cctv/check/<int:pk>/', views.check, name='check'),
    path('record/', views.record, name='record'),
    path('lists/police/', views.police_list, name='police-list'),
    path('lists/guard/', views.guard_list, name='guard-list'),
    path('send/<int:alarm_pk>/', views.send, name='send')
]

templates/base.html
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>도로시</title>
    <!-- Custom fonts for this template -->
    <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/sb-admin-2.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet">

        <!-- Bootstrap core CSS -->
        <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static "css/simple-sidebar.css" %}" rel="stylesheet">
        <script type="text/javascript"
                src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=u7319e28n1"></script>
</head>

<body>

<div class="d-flex" id="wrapper">
<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url "map:main" %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"> 도로시 <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>프로필</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link" href="{% url "map:record" %}" >
          <i class="fas fa-fw fa-cog"></i>
          기록 조회
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
          <a class="nav-link" href="#collapsePages" data-toggle="collapse" data-targer="#collapsePages">
              <i class="fas fa-fw fa-wrench"></i>
              인력조회
          </a>
          <div id="collapsePages" class="collapse" aria-labelledby="headingPages">
              <div class="bg-white py-2 collapse-inner rounded">
                  <h6 class="collapse-header">목록</h6>
                  <a class="collapse-item" href="{% url 'map:police-list'%}">시간별 담당 경찰 조회</a>
                  <a class="collapse-item" href="{% url 'map:guard-list'%}">지킴이 조회</a>
              </div>
          </div>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
{#      <li class="nav-item">#}
{#        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">#}
{#          <i class="fas fa-fw fa-folder"></i>#}
{#          <span>Pages</span>#}
{#        </a>#}
{#        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">#}
{#          <div class="bg-white py-2 collapse-inner rounded">#}
{#            <h6 class="collapse-header">Login Screens:</h6>#}
{#            <a class="collapse-item" href="login.html">Login</a>#}
{#            <a class="collapse-item" href="register.html">Register</a>#}
{#            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>#}
{#            <div class="collapse-divider"></div>#}
{#            <h6 class="collapse-header">Other Pages:</h6>#}
{#            <a class="collapse-item" href="404.html">404 Page</a>#}
{#            <a class="collapse-item" href="blank.html">Blank Page</a>#}
{#          </div>#}
{#        </div>#}
{#      </li>#}

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>

      <!-- Nav Item - Tables -->
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="tables.html">#}
{#          <i class="fas fa-fw fa-table"></i>#}
{#          <span>Tables</span></a>#}
{#      </li>#}

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
    <!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->

<!-- Bootstrap core JavaScript-->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static "js/sb-admin-2.min.js" %}"></script>

  <!-- Page level plugins -->
  <script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
  <script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

  <!-- Page level custom scripts -->
{#  <script src="{% static "js/demo/datatables-demo.js" %}"></script>#}

<!-- Menu Toggle Script -->
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>